_target_: pangaea.datasets.austrian_crop.AustrianCrop
dataset_name: AustrianCrop
root_path: ./data/austrian_crop_v1.0_pipeline_prithvi
# root_path: /shared/amdgpu/home/avsm2_f4q/code/pangaea-bench/data/austrian_crop_v1.0_pipeline_prithvi
download_url: null
auto_download: False

img_size: 64  # 根据你的实际patch大小调整
multi_temporal: 6
multi_modal: True

# classes
ignore_index: -1  # 如果没有忽略类别，设为-1
num_classes: 18
classes: 
  - Background
  - Legume
  - Soy
  - Summer Grain
  - Winter Grain
  - Corn
  - Sunflower
  - Mustard
  - Potato
  - Beet
  - Squash
  - Grapes
  - Tree Fruit
  - Cover Crop
  - Grass
  - Fallow
  - Other (Plants)
  - Other (Non Plants)

# TODO: 这些distribution数据需要自行计算修改
distribution:
  - 0.00000  # Background (excluded, 8,759,944 pixels)
  - 0.03275  # Legume (256,920 pixels, 3.27% of non-bg)
  - 0.08817  # Soy (691,749 pixels, 8.82% of non-bg)
  - 0.03673  # Summer Grain (288,155 pixels, 3.67% of non-bg)
  - 0.37039  # Winter Grain (2,905,807 pixels, 37.04% of non-bg)
  - 0.10215  # Corn (801,392 pixels, 10.22% of non-bg)
  - 0.00317  # Sunflower (24,850 pixels, 0.32% of non-bg)
  - 0.02550  # Mustard (200,041 pixels, 2.55% of non-bg)
  - 0.03757  # Potato (294,759 pixels, 3.76% of non-bg)
  - 0.01855  # Beet (145,498 pixels, 1.85% of non-bg)
  - 0.02998  # Squash (235,226 pixels, 3.00% of non-bg)
  - 0.00337  # Grapes (26,466 pixels, 0.34% of non-bg)
  - 0.00529  # Tree Fruit (41,506 pixels, 0.53% of non-bg)
  - 0.02078  # Cover Crop (163,014 pixels, 2.08% of non-bg)
  - 0.03503  # Grass (274,805 pixels, 3.50% of non-bg)
  - 0.06699  # Fallow (525,528 pixels, 6.70% of non-bg)
  - 0.12278  # Other (Plants) (963,215 pixels, 12.28% of non-bg)
  - 0.00080  # Other (Non Plants) (6,309 pixels, 0.08% of non-bg)

bands:
  optical:
    - B4
    - B2
    - B3
    - B8
    - B8A
    - B5
    - B6
    - B7
    - B11
    - B12
  sar:
    - VV
    - VH

# TODO: 这些统计数据需要自行计算修改
data_mean:
  optical:
    - 1032.6992  # Band 1
    - 747.6366  # Band 2
    - 966.1728  # Band 3
    - 2637.6731  # Band 4
    - 2701.3318  # Band 5
    - 1402.8016  # Band 6
    - 2197.8057  # Band 7
    - 2502.8484  # Band 8
    - 2333.1937  # Band 9
    - 1779.6444  # Band 10
  sar:
    - -10.9433
    - -17.3600

# TODO: 这些统计数据需要自行计算修改
data_std:
  optical:
    - 641.3223  # Band 1
    - 536.6477  # Band 2
    - 539.0782  # Band 3
    - 1019.4687  # Band 4
    - 1016.4736  # Band 5
    - 610.8468  # Band 6
    - 829.1185  # Band 7
    - 1001.1198  # Band 8
    - 736.9046  # Band 9
    - 755.6927  # Band 10
  sar:
    - 3.3847
    - 3.3727

# TODO: 这些统计数据需要自行计算修改
data_min:
  optical: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  sar: [-39.5312, -43.1250]

# TODO: 这些统计数据需要自行计算修改  
data_max:
  optical: [18264.0, 21192.0, 19512.0, 16664.0, 16405.0, 17617.0, 16900.0, 16579.0, 15486.0, 15307.0]
  sar: [34.8750, 27.3125]